### ISSUE TITLE
Create test data directory

### ISSUE THREAD

**Issue by annapamma** [sgosline/proteomicsTumorDeconv#102]
Create slimmed down test data directory

**Comment by annapamma** [comment]
Started here: https://github.com/sgosline/proteomicsTumorDeconv/tree/anna-test-data

My main question is whether I should remove the test examples from the imputation and repBulk directories. In which case, I just need to update the READMEs to reflect the new paths to the test data.

**Comment by sgosline** [comment]
This is great - I think that for the tests for each algorithm we should have:
1- run on this test dataset (on all the matrices)
2- run the correlation script on the mRNA/protein (on one matrix?)
This to me, seems like it would be the "bare minimum" for submitting a new algorithm to the repository.  What do you think?

**Comment by annapamma** [comment]
Yes that sounds good to me. If I understand correctly:
- I should write tests running each of the algorithms on this test data
- Future algorithms should be tested on this data

Which correlation script are we talking about here? I don't think I've tested running this yet.
