### ISSUE TITLE
Epic docker image fails on ccrcc tumor proteomics with PBMC matrix

### ISSUE THREAD

**Issue by sgosline** [sgosline/proteomicsTumorDeconv#113]
I think we can simply add a try/catch statement and return a 1/0 for this call here:

```
Error in cor.test.default(b, b_estimated, method = "spearman") :
  not enough finite observations
Calls: EPIC -> lapply -> FUN
```

**Comment by sgosline** [comment]
Also fails for LUAD.

**Comment by LifeWorks** [comment]
I was thinking the same thing yesterday. I will make a pull request soon to the main.

**Comment by LifeWorks** [comment]
I went back to check the PBMC signature matrices. I think these signature matrices are not derived in a consistent approach. Some are clearly using log scale some are using absolute scale. 

Besides applying the try/catch, I will also update the signature refProfiles to accommodate the signature matrices. 

It seems very messy that all these methods and signature matrices were not crafted and derived in a unified way.

**Comment by LifeWorks** [comment]
> Also fails for LUAD.

Apparently it is not working for almost all cancer types with PBMC. So it must be the problem of PBMC's ref profile. Other algorithms that are not using ref profile run well.

**Comment by LifeWorks** [comment]
> I went back to check the PBMC signature matrices. I think these signature matrices are not derived in a consistent approach. Some are clearly using log scale some are using absolute scale.
> 
> Besides applying the try/catch, I will also update the signature refProfiles to accommodate the signature matrices.
> 
> It seems very messy that all these methods and signature matrices were not crafted and derived in a unified way.

OK, it is not the log scale vs abs scale. It is rather that PBMC_refMean contains NAs
