### ISSUE TITLE
Identify summary statistic (or set of statistics) to  compare two deconvoluted matrices

### ISSUE THREAD

**Issue by sgosline** [sgosline/proteomicsTumorDeconv#123]
Currently we are comparing matrices by rows or columns using the correlation. These one-dimensional comparisons are useful but incomplete. If we can identify a two-dimensional statistic that accounts for differences across scale we should use that as one of our earlier figures. Possible some sort of distance? normalize distance? Ideas welcome.

**Comment by sgosline** [comment]
To compare distributions we first need to normalize all samples to sum to 1 (so that each cell assignment represents a 'fraction' of the total tumor. 

Then we can compare:
1- euclidean distance for entire matrix
2- mean KS test statistic between samples across all samples
3- mean KL distance between samples across all samples

**Comment by sgosline** [comment]
@LifeWorks  will do the above, while @sgosline  will update the figure plots.

**Comment by LifeWorks** [comment]
Finished implementing the three more distances: Euclidean distance, Jensen-Shannon divergence, Kolmogorov-Smirnov divergence. #131

**Comment by LifeWorks** [comment]
resolved
