### ISSUE TITLE
Add in new metrics to existing workflows

### ISSUE THREAD

**Issue by sgosline** [sgosline/proteomicsTumorDeconv#134]
Add in new metrics and plotting to existing workflows that evaluate mrna-prot correlation across all datasets and simulated data.

**Comment by sgosline** [comment]
@LifeWorks I'm nearly done with this, but can you point me to the code that does the heatmaps?

**Comment by LifeWorks** [comment]
I will push it into main soon.

**Comment by LifeWorks** [comment]
Oh, I think it is more complicated. I will work on it today.

**Comment by sgosline** [comment]
I think this is nearly done, in the ipynb - just need to collect files and plot in a single script.

**Comment by LifeWorks** [comment]
Currently, the combine_results.R can generate the heatmaps. We don't need extra python code to plot heatmap. The pipeline would be just the same as the correlation plot

**Comment by LifeWorks** [comment]
oops, now I know what you mean. Because of the simulated data is not using the cptac data, so it can not be directly used.

**Comment by LifeWorks** [comment]
The combine_results.R should be ready to use now. Just need to change the parameters in cwl files to match the plot-fig docker image and cwl.
