### ISSUE TITLE
Error running the tool

### ISSUE THREAD

**Issue by pietrisko** [sgosline/proteomicsTumorDeconv#136]
I got this crash with this example command:

cwltool scatter-test.cwl --cancerTypes ccrcc --mrna-algorithms xcell --prot-algorithms xcell --signatures ../signature_matrices/LM22.txt --tissueTypes all

Combining 2 files
Error in file(file, "rt") : cannot open the connection
Calls: main ... combinePatientCors -> do.call -> lapply -> FUN -> read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'correlation': No such file or directory
Execution halted
INFO [job get-patient-cors] Max memory used: 144MiB
ERROR [job get-patient-cors] Job error:
("Error collecting output for parameter 'table':\nfigures/plot-figs.cwl:36:9: Did not find output file with glob pattern: '['*.tsv']'", {})
WARNING [job get-patient-cors] completed permanentFail
ERROR [step get-patient-cors] Output is missing expected field file:///Users/pietro/Documents/GitHub/proteomicsTumorDeconv/perfEval/scatter-test.cwl#scatter-test/get-patient-cors/table
ERROR [step get-patient-cors] Output is missing expected field file:///Users/pietro/Documents/GitHub/proteomicsTumorDeconv/perfEval/scatter-test.cwl#scatter-test/get-patient-cors/fig
[step get-patient-cors] completed permanentFail

**Comment by sgosline** [comment]
Pietro what branch are you on?

**Comment by sgosline** [comment]
Ok. I've never tried running with only a single cancer type and algorithm. Can you run with the scatter test yaml file?

**Comment by sgosline** [comment]
Actually I was able to run that command from the `main` branch. Do you receive any other errors?

**Comment by LifeWorks** [comment]
> I got this crash with this example command:
> 
> cwltool scatter-test.cwl --cancerTypes ccrcc --mrna-algorithms xcell --prot-algorithms xcell --signatures ../signature_matrices/LM22.txt --tissueTypes all
> 
> Combining 2 files
> Error in file(file, "rt") : cannot open the connection
> Calls: main ... combinePatientCors -> do.call -> lapply -> FUN -> read.table -> file
> In addition: Warning message:
> In file(file, "rt") :
> cannot open file 'correlation': No such file or directory
> Execution halted
> INFO [job get-patient-cors] Max memory used: 144MiB
> ERROR [job get-patient-cors] Job error:
> ("Error collecting output for parameter 'table':\nfigures/plot-figs.cwl:36:9: Did not find output file with glob pattern: '['*.tsv']'", {})
> WARNING [job get-patient-cors] completed permanentFail
> ERROR [step get-patient-cors] Output is missing expected field file:///Users/pietro/Documents/GitHub/proteomicsTumorDeconv/perfEval/scatter-test.cwl#scatter-test/get-patient-cors/table
> ERROR [step get-patient-cors] Output is missing expected field file:///Users/pietro/Documents/GitHub/proteomicsTumorDeconv/perfEval/scatter-test.cwl#scatter-test/get-patient-cors/fig
> [step get-patient-cors] completed permanentFail

Hi, Peitro, can you try to use the yaml file rather than using the command line? I suspect the problem is that some steps in scattering pipeline expect you provide many deconvoluted tables.

**Comment by pietrisko** [comment]
OK, now it works. I deleted the previous images with 'docker image prune -a'. Thanks @sgosline
