### ISSUE TITLE
Change the processing of signature matrices and make it consist across algorithms

### ISSUE THREAD

**Issue by LifeWorks** [sgosline/proteomicsTumorDeconv#78]
As discussed with @annapamma and Francesca, we decide to use the following approach:

1. Using 0.75 to get the high expression marker genes for each cell type (removing the noisy values)
2. Implement two options of filtering:
- [x] Take marker genes that has at least 2 fold change over the mean of all cell types (this will be the default option)
- [x] Take marker genes that has at least 2 fold change over all other cell types
3. The two options can be used to assess the quality of signature matrices in the future, i.e. how specific are these marker genes for the cell types, especially for these sig matrices derived from single-cell omics data.

**Comment by annapamma** [comment]
@LifeWorks Thanks for writing this code! I tried running the bit of code I think is for processing signature matrices for LM9, and I had a hard time interpreting the output. Are you free tomorrow after the call to walk me through it?

I want to add this bit of code to repBulk, so it can just accept a signature matrix as input.

Thanks!

**Comment by LifeWorks** [comment]
> @LifeWorks Thanks for writing this code! I tried running the bit of code I think is for processing signature matrices for LM9, and I had a hard time interpreting the output. Are you free tomorrow after the call to walk me through it?
> 
> I want to add this bit of code to repBulk, so it can just accept a signature matrix as input.
> 
> Thanks!

OK, no problem.

**Comment by sgosline** [comment]
Per conversation during our meeting, we will change the quantile to 0.5.

**Comment by sgosline** [comment]
Update - the quantile is not the issue, but the mean vs. median. @LifeWorks is going to test out.

**Comment by LifeWorks** [comment]
Now it is gracefully handled. I created the pull request. Even the median there is no genes have 2 fold more than median across cell types. But I manage to make the safe guard option more biologically meaningful. Using quantile of differential expression values.
