### ISSUE TITLE
Problem of EPIC identified, but seems not solvable unless we provide the reference profile as well.

### ISSUE THREAD

**Issue by LifeWorks** [sgosline/proteomicsTumorDeconv#80]
The high correlation across samples and low correlation across cell types should be due to the reference profile was set as the signature matrix directly, which should be the genome-wide expression table used to derive the signature matrix. If not provided it will use EPIC's own marker gene list and reference profile, which doesn't have the issue.

**Comment by sgosline** [comment]
Resolution:
1- @pietrisko will put the signature matrices on figshare
2- @sgosline will rebuild docker with the files locally
3-  @LifeWorks will then update the r code to load these in locally.

**Comment by pietrisko** [comment]
https://ndownloader.figshare.com/files/26488094 ##lm7c
https://ndownloader.figshare.com/files/26488223 ##lm9
https://ndownloader.figshare.com/files/26488313 ##PBMC

**Comment by LifeWorks** [comment]
> Here the genome-wide expression tables for the signature matrices:
> 
> https://ndownloader.figshare.com/files/26488094 ##lm7c
> https://ndownloader.figshare.com/files/26488223 ##lm9
> https://ndownloader.figshare.com/files/26488313 ##PBMC

Thanks, Pietro. Do you have the profile for LM21?

**Comment by LifeWorks** [comment]
OK. I found LM22 and will need to process all the ref profile to make them usable for epic. Once I process them, will upload to figshare.

**Comment by pietrisko** [comment]
I also found LM22 reference matrix and process it to have usable sample names and the exact samples they used, please check if it's identical to the yours.

https://ndownloader.figshare.com/files/26504420

**Comment by sgosline** [comment]
I unassigned myself, The docker image will take a while to build, but once built will have the four matrix files in the /data/ directory (i renamed them to matrixname_ref.txt).

**Comment by sgosline** [comment]
shoot i put it in the wrong docker file. whoops.

**Comment by sgosline** [comment]
Ok, now the epic docker file is corrected.

**Comment by LifeWorks** [comment]
> Ok, now the epic docker file is corrected.

The file need to be preprocessed. I will preprocess them and reupload them to figshare and update the dockerfile later today or early tomorrow,

**Comment by LifeWorks** [comment]
Solved

**Comment by sgosline** [comment]
Can you link to the PR for this? I want to make sure that the matrices will be added in the perfEval script.

**Comment by LifeWorks** [comment]
> Can you link to the PR for this? I want to make sure that the matrices will be added in the perfEval script.

They are #98 and #99
