### ISSUE TITLE
Requesting README for how to run xCell

### ISSUE THREAD

**Issue by annapamma** [sgosline/proteomicsTumorDeconv#89]
Downloading and imputation are now rolling in the end-to-end testing framework.

I'd like to start testing a tumor deconvolution algorithms. Since repBulk is still under development, xCell seemed like a good place to start. 

@LifeWorks when you get a chance, can you add a README for how to run the xCell cwltool? That'll make it easier for me to play around with testing!

**Comment by LifeWorks** [comment]
`cwltool --debug run-xcell-tool.cwl --expression file.tsv --signature LM9.txt --type tumor --cancerType ccrcc`

**Comment by LifeWorks** [comment]
I am closing this one
