### ISSUE TITLE
Problem with cwl 

### ISSUE THREAD

**Issue by pietrisko** [sgosline/proteomicsTumorDeconv#90]
I could not run cwl with cwl files version 'v1.2', I have to change 'cwlVersion' in the cwl files to: 'v1.2.0-dev3' and run cwl adding '--enable-dev'

**Comment by sgosline** [comment]
Via email @pietrisko told me he was running `cwltool` version 3.0.20200710214758. Pietro, can you please let me know which version of python you're running as well? I can't reproduce this error.

**Comment by pietrisko** [comment]
3.8.5

**Comment by annapamma** [comment]
I'll have to create a virtualenv with Python3.8 and try this, but I wanted to get some information first. I noticed there is a mix of CWL versions in the repo.

@pietrisko Is this just happening with CWL v1.2 or are you encountering this with the CWL v1.0 files as well? I've been working with 1.2, a later version of CWL (3.0.2021012) but Python 3.6. 
 
Also, can you show the error you are getting when you try to run cwl version 1.2? Thanks!

**Comment by annapamma** [comment]
According to this [cwltool release ](https://github.com/common-workflow-language/cwltool/releases/tag/3.0.20200807132242), it seems that versions before August were not compatible with CWL v1.2. It looks like your cwltool is from July.

Can you try updating your CWL tool? You can run this command: 
```
pip install --upgrade cwltool
```

or 

```
pip3 install --upgrade cwltool
```

if you're using pip3.

**Comment by sgosline** [comment]
We require v1.2 to run, so need the more advanced tool. I'm not sure about which python to require. I've been running 3.7. At least we have 3 versions covered?

**Comment by annapamma** [comment]
@pietrisko Did upgrading cwltool help with this?

**Comment by pietrisko** [comment]
Yes! thanks a lot @annapamma
